// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuieroUn10.Data;

namespace QuieroUn10.Migrations
{
    [DbContext(typeof(QuieroUnDiezDBContex))]
    [Migration("20210415160400_actualizacionMigracion")]
    partial class actualizacionMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuieroUn10.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserAccountId");

                    b.ToTable("ADMIN");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Admin1",
                            Phone = "698756483",
                            Surname = "Admin1",
                            UserAccountId = 1
                        },
                        new
                        {
                            ID = 2,
                            Name = "Admin2",
                            Phone = "698756483",
                            Surname = "Admin2",
                            UserAccountId = 2
                        });
                });

            modelBuilder.Entity("QuieroUn10.Models.CalendarTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DayEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DayStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StudentId");

                    b.ToTable("CALENDAR_TASK");
                });

            modelBuilder.Entity("QuieroUn10.Models.Doc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("DocByte")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DocContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocSourceFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentHasSubjectId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StudentHasSubjectId");

                    b.ToTable("DOC");
                });

            modelBuilder.Entity("QuieroUn10.Models.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("MENU");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Action = "Index",
                            Controller = "UserAccounts",
                            Label = "User Accounts"
                        },
                        new
                        {
                            ID = 2,
                            Action = "Index",
                            Controller = "Roles",
                            Label = "Roles"
                        },
                        new
                        {
                            ID = 3,
                            Action = "Index",
                            Controller = "Students",
                            Label = "Students"
                        },
                        new
                        {
                            ID = 4,
                            Action = "Index",
                            Controller = "Admins",
                            Label = "Admins"
                        },
                        new
                        {
                            ID = 5,
                            Action = "Index",
                            Controller = "Menus",
                            Label = "Menus"
                        },
                        new
                        {
                            ID = 6,
                            Action = "Index",
                            Controller = "Studies",
                            Label = "Studies"
                        },
                        new
                        {
                            ID = 7,
                            Action = "Index",
                            Controller = "Subjects",
                            Label = "Subjects"
                        },
                        new
                        {
                            ID = 8,
                            Action = "Index",
                            Controller = "StudyHasSubjects",
                            Label = "Study Has Subjects"
                        },
                        new
                        {
                            ID = 9,
                            Action = "Index",
                            Controller = "CalendarTasks",
                            Label = "Calendar Tasks"
                        },
                        new
                        {
                            ID = 10,
                            Action = "Index",
                            Controller = "Docs",
                            Label = "Documents"
                        },
                        new
                        {
                            ID = 11,
                            Action = "Index",
                            Controller = "StudentHasSubjects",
                            Label = "Student Subjects"
                        },
                        new
                        {
                            ID = 12,
                            Action = "Index",
                            Controller = "Tasks",
                            Label = "Tasks"
                        },
                        new
                        {
                            ID = 13,
                            Action = "Details",
                            Controller = "AdminDtoes",
                            Label = "Profile"
                        },
                        new
                        {
                            ID = 14,
                            Action = "Details",
                            Controller = "StudentDtoes",
                            Label = "Profile"
                        });
                });

            modelBuilder.Entity("QuieroUn10.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("ROLE");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Enabled = false,
                            Name = "ADMIN"
                        },
                        new
                        {
                            ID = 2,
                            Enabled = false,
                            Name = "STUDENT"
                        });
                });

            modelBuilder.Entity("QuieroUn10.Models.RoleHasMenu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("ROLE_HAS_MENU");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MenuId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 2,
                            MenuId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 3,
                            MenuId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 4,
                            MenuId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 5,
                            MenuId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 6,
                            MenuId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 7,
                            MenuId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 8,
                            MenuId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 9,
                            MenuId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 10,
                            MenuId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 11,
                            MenuId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 12,
                            MenuId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            ID = 13,
                            MenuId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            ID = 14,
                            MenuId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            ID = 15,
                            MenuId = 14,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("QuieroUn10.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activate")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserAccountId");

                    b.ToTable("STUDENT");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Activate = false,
                            Birthdate = new DateTime(1999, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alejandro",
                            Phone = "620730065",
                            Surname = "Cruz",
                            UserAccountId = 3
                        });
                });

            modelBuilder.Entity("QuieroUn10.Models.StudentHasSubject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InscriptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("STUDENT_HAS_SUBJECT");
                });

            modelBuilder.Entity("QuieroUn10.Models.Study", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("STUDY");
                });

            modelBuilder.Entity("QuieroUn10.Models.StudyHasSubject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StudyId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StudyId");

                    b.HasIndex("SubjectId");

                    b.ToTable("STUDY_HAS_SUBJECT");
                });

            modelBuilder.Entity("QuieroUn10.Models.Subject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("SUBJECT");
                });

            modelBuilder.Entity("QuieroUn10.Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllDay")
                        .HasColumnType("bit");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentHasSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StudentHasSubjectId");

                    b.ToTable("TASK");
                });

            modelBuilder.Entity("QuieroUn10.Models.UserAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("RoleId");

                    b.ToTable("USER_ACCOUNT");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Active = true,
                            Email = "admin1@gmail.com",
                            Password = "YQBkAG0AaQBuADEA",
                            RoleId = 1,
                            Username = "admin1"
                        },
                        new
                        {
                            ID = 2,
                            Active = true,
                            Email = "admin2@gmail.com",
                            Password = "YQBkAG0AaQBuADIA",
                            RoleId = 1,
                            Username = "admin2"
                        },
                        new
                        {
                            ID = 3,
                            Active = true,
                            Email = "student1@gmail.com",
                            Password = "cwB0AHUAZABlAG4AdAAxAA==",
                            RoleId = 2,
                            Username = "student1"
                        });
                });

            modelBuilder.Entity("QuieroUn10.Models.UserToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Life")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserAccountId");

                    b.ToTable("USER_TOKEN");
                });

            modelBuilder.Entity("QuieroUn10.Models.Admin", b =>
                {
                    b.HasOne("QuieroUn10.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("QuieroUn10.Models.CalendarTask", b =>
                {
                    b.HasOne("QuieroUn10.Models.Student", "Student")
                        .WithMany("CalendarTasks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuieroUn10.Models.Doc", b =>
                {
                    b.HasOne("QuieroUn10.Models.StudentHasSubject", "StudentHasSubject")
                        .WithMany("Docs")
                        .HasForeignKey("StudentHasSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentHasSubject");
                });

            modelBuilder.Entity("QuieroUn10.Models.RoleHasMenu", b =>
                {
                    b.HasOne("QuieroUn10.Models.Menu", "Menu")
                        .WithMany("RoleHasMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuieroUn10.Models.Role", "Role")
                        .WithMany("RoleHasMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuieroUn10.Models.Student", b =>
                {
                    b.HasOne("QuieroUn10.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("QuieroUn10.Models.StudentHasSubject", b =>
                {
                    b.HasOne("QuieroUn10.Models.Student", "Student")
                        .WithMany("StudentHasSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuieroUn10.Models.Subject", "Subject")
                        .WithMany("StudentHasSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QuieroUn10.Models.StudyHasSubject", b =>
                {
                    b.HasOne("QuieroUn10.Models.Study", "Study")
                        .WithMany("StudyHasSubjects")
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuieroUn10.Models.Subject", "Subject")
                        .WithMany("StudyHasSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QuieroUn10.Models.Task", b =>
                {
                    b.HasOne("QuieroUn10.Models.StudentHasSubject", "StudentHasSubject")
                        .WithMany("Tasks")
                        .HasForeignKey("StudentHasSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentHasSubject");
                });

            modelBuilder.Entity("QuieroUn10.Models.UserAccount", b =>
                {
                    b.HasOne("QuieroUn10.Models.Role", "Role")
                        .WithMany("UserAccounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuieroUn10.Models.UserToken", b =>
                {
                    b.HasOne("QuieroUn10.Models.UserAccount", "UserAccount")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("QuieroUn10.Models.Menu", b =>
                {
                    b.Navigation("RoleHasMenus");
                });

            modelBuilder.Entity("QuieroUn10.Models.Role", b =>
                {
                    b.Navigation("RoleHasMenus");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("QuieroUn10.Models.Student", b =>
                {
                    b.Navigation("CalendarTasks");

                    b.Navigation("StudentHasSubjects");
                });

            modelBuilder.Entity("QuieroUn10.Models.StudentHasSubject", b =>
                {
                    b.Navigation("Docs");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("QuieroUn10.Models.Study", b =>
                {
                    b.Navigation("StudyHasSubjects");
                });

            modelBuilder.Entity("QuieroUn10.Models.Subject", b =>
                {
                    b.Navigation("StudentHasSubjects");

                    b.Navigation("StudyHasSubjects");
                });

            modelBuilder.Entity("QuieroUn10.Models.UserAccount", b =>
                {
                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
